name: Twitch CDK Mining

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  cdk:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - name: Run CDK Mining
        working-directory: cdk_linux
        run: bash run.sh
